### PR TITLE
Adding ability to run external router

### PR DESCRIPTION
**Pull request by gooseleggs**
This PR adds the ability to stand up a router outside of the docker quickstart environment.  
The script does not use the `ziti.env` configuration file and requires on first run that all required variables are passed through on first run.

**To use**
create a docker-compose file including the following configuration:

```
  ziti-edge-router:
    environment:
      - ZITI_EDGE_ROUTER_RAWNAME_OVERRIDE=*URL or IP clients connect to router*
      - ZITI_EDGE_ROUTER_ROLES=*roles to assign*
      - ZITI_EDGE_ROUTER_PORT=*normally 3022*
      - ZITI_EDGE_ROUTER_LISTENER_BIND_PORT=*router fabric port*
      - ZITI_CTRL_PORT=*controller management port*
      - ZITI_EDGE_CONTROLLER_PORT_OVERRIDE=*normally 1280*
      - ZITI_CTRL_ADVERTISED_ADDRESS_OVERRIDE=*controller_FQDN_Name or IP*
      - ZITI_USER_OVERRIDE=*admin username*
      - ZITI_PWD_OVERRIDE=*admin password*
    command: "/var/openziti/scripts/run-router-external.sh edge"
```

when you start the container, a new router configuration is created and then started.  As per other scripts, the type of router created is specified in the *command* option (in this case edge).

Once the router is up and going, then all environment variables except the *ZITI_EDGE_ROUTER_RAWNAME_OVERRIDE* can be removed, as the other variables are only required for the generation of the configuration.

### CODE REVIEW

**Comment by gooseleggs** [comment]
Not sure how to link to the issue, but here it is here: https://github.com/openziti/ziti/issues/967

**Comment by gooseleggs** [comment]
Note that there are *new* configuration directives with `_OVERRIDE` in the name.  This was necessary as when you log into bash it loads the `ziti.env` file automatically.  This will then clobber any similar named variables that are passed in the from the container.

I didn't want to use the `ziti-env` file as:
- It contains a large number of variables which is difficult to understand what ones are required to be changed
- Requires that the `ziti.env` file is bind mounted into the container, or manually copied in
- More secure as without a ziti.env file they only have the `.yaml` file with configuration (assuming you drop the other environment variables)

**Comment by gooseleggs** [comment]
Just issued another commit.  This allows for the name to be defined within the controller.  I have added an additional variable: `ZITI_EDGE_ROUTER_HOSTNAME`.  This variable defines the name that will appear in the console.

So, list of variables now:

```
  ziti-edge-router:
    environment:
      - ZITI_EDGE_ROUTER_RAWNAME_OVERRIDE=*URL or IP clients connect to router*
      - ZITI_EDGE_ROUTER_HOSTNAME=*name to show in the console*
      - ZITI_EDGE_ROUTER_ROLES=*roles to assign*
      - ZITI_EDGE_ROUTER_PORT=*normally 3022*
      - ZITI_EDGE_ROUTER_LISTENER_BIND_PORT=*router fabric port*
      - ZITI_CTRL_PORT=*controller management port*
      - ZITI_EDGE_CONTROLLER_PORT_OVERRIDE=*normally 1280*
      - ZITI_CTRL_ADVERTISED_ADDRESS_OVERRIDE=*controller_FQDN_Name or IP*
      - ZITI_USER_OVERRIDE=*admin username*
      - ZITI_PWD_OVERRIDE=*admin password*
    command: "/var/openziti/scripts/run-router-external.sh edge"
```

Once the configuration is all up and going, then it is not just the `ZITI_EDGE_ROUTER_HOSTNAME` variable that needs to stay.

**Comment by gberl002** [comment]
> Not sure how to link to the issue, but here it is here: #967

Use any of the keywords followed by `#id`, see the keywords [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

closes #967

**Comment by gberl002** [comment]
This looks good, would you mind creating a `ziti-doc` PR and adding some instructions on how you would use this? @dovholuknf might have an opinion here but I think tacking the usage of this onto the end of the "Quickstart with Docker" and/or "Quickstart Docker Compose".

I'm not sure how familiar with docker you are but docker profiles could also help here. We could have two profiles, one for the "local docker compose" and another for the "external" so when you run docker-compose up it only starts up the external router when using the "external" profile and create a "local" profile.

As an example, you would run this to start up the controller, router(s) and such on the controller's host machine
`docker compose --profile local up`

And run this on machine with the external router
`docker compose --profile external up`

 
In any case, we may want to consider updating the topic from "Local - With Docker" and "Local - Docker Compose" to just simply remove the "Local -" prefix since we're moving toward allowing docker-compose to work in external environments. Any thoughts on this would be helpful.

**Comment by gooseleggs** [comment]
I will create docs for it but was waiting to find out if this makes it in and what changes are requested to be done.  Didn’t want doc accepted before code is their :-). 

Haven’t played with profiles before so will look into that.   I normally just cut down the compose file to only the required sections for readability.  

As for doc location I was thinking making a guide regarding standing up and external router and have both docker and standard commands in the one document.

**Comment by gberl002** [comment]
@gooseleggs sorry about bouncing around, but we are planning on making some changes in the architecture of the docker files so you can skip the doc and profile stuff for now as it will inevitably change.

So, I think this looks good as is.

**Review by gberl002 — APPROVED** [review]

**Comment by gooseleggs** [comment]
When are you looking at changing the files? I think it is still worthwhile to create the doc as then something is available to all.  That said it will be next week before I can look at it.

**Comment by dovholuknf** [comment]
We are still in the midst of changing them. There have been new container images posted to docker hub that make no assumptions about setup, don't "do" anything on your behalf, and just run the provided config file. you might find those useful @gooseleggs . 

I plan to get back to using those in a 'quickstart' fashion soon but if not me I'd think @gberl002 would be... I'd like to say "a week or two" but it might be longer.

**Comment by dovholuknf** [comment]
@gberl002 can you take a look at this pr and let's decide if it's in the direction we're looking at going next? thanks!

**Comment by gooseleggs** [comment]
I like easy.  Will wait for the hopefully setup like this PR provides across the containers.  I have a few to set up in the following weeks, so will look to use the current docker containers, and use this PR where required. Hopefully any changes wont be catastrophic to migrate too.  Would do testing and feedback if required.  Let me know if I can help in any way.
Hopefully doing this, we can sort out the variable names as well?

**Comment by dovholuknf** [comment]
@gberl002 has been working on cleaning up the env variable names. so hopefully. i'll let him comment on that, i know he's making progress but haven't seen anything just yet

**Comment by gberl002** [comment]
Sorry, I kind of dropped the ball here. I was expecting to merge this in and then was hesitant with all the quickstart changes coming soon.

I'll take a closer look at this tomorrow now that I'm mostly done with the cleanup. I'll see how it aligns with the current work.

**Pull request merged**
