### PR TITLE
ci: Add dependabot configuration for github-actions

### LINKED ISSUE #1745: CI: Outdated GitHub actions
Hi,

Would you like to enable dependabot for this repo?

IMHO, at least for *github-actions* it would be a good enhancement. Otherwise, golang would possible as well, for updating the whole module vendoring.

If you agree, I can submit a PR for this.

Thank you!

### PR DESCRIPTION
**Pull request by mjtrangoni**
Hi @plorenz,

This fixes #1745. I just took the same frequency config as gomod, but normally I prefer running it in a weekly basic.

Open for changing it to the desired value.

Thank you!

### CODE REVIEW

**Comment by plorenz** [comment]
> Hi @plorenz,
> 
> This fixes #1745. I just took the same frequency config as gomod, but normally I prefer running it in a weekly basic.
> 
> Open for changing it to the desired value.
> 
> Thank you!

Weekly sounds good :+1:

**Comment by mjtrangoni** [comment]
@plorenz done

**Review by plorenz — APPROVED** [review]

**Comment by plorenz** [comment]
One more ask, could you sign your commit, please? See https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by mjtrangoni** [comment]
> One more ask, could you sign your commit, please? See https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

good catch! Done

**Comment by plorenz** [comment]
@mjtrangoni Thank you for contributing this!

**Pull request merged**
