### PR TITLE
Adding CI support for MacOS arm

### LINKED ISSUE #652: Update CLI script M1 Support when github actions allows
Currently github actions don't support pushing darwin arm distros. The CLI script currently works around this by pulling the darwin amd distro. Once github actions supports darwin arm the CLI script will need to be updated to pull the correct distro.

Appropriate build scripts will need to be updated as well so we actually push a darwin arm distro

https://github.com/actions/runner/issues/805

### PR DESCRIPTION
**Pull request by gberl002**
Closes #652

### CODE REVIEW

**Comment by plorenz** [comment]
Just a reminder that you have to put the 'fixes #<bug number>' on the commit, not the PR

**Review by plorenz — APPROVED** [review]

**Comment by qrkourier** [comment]
> Just a reminder that you have to put the 'fixes #' on the commit, not the PR

It'll work on the PR as long as the resolution keyword appears in the description, not a comment, which merely cross-links the GH issue.

**Comment by plorenz** [comment]
> > Just a reminder that you have to put the 'fixes #' on the commit, not the PR
> 
> It'll work on the PR as long as the resolution keyword appears in the description, not a comment, which merely cross-links the GH issue.

It doesn't work with the ziti-ci build-release-notes tool. It would be a nice addition, but it's not currently supported.

**Comment by gberl002** [comment]
> Just a reminder that you have to put the 'fixes #' on the commit, not the PR

I did, it put the commit message in as the PR description automatically.

**Comment by plorenz** [comment]
> > Just a reminder that you have to put the 'fixes #' on the commit, not the PR
> 
> I did, it put the commit message in as the PR description automatically.

Ah, I checked the commits, but it was on a new line, and I had to expand to see it. Apologies!

**Pull request merged**
