### PR TITLE
changelog what's new: docker images

### PR DESCRIPTION
**Pull request by qrkourier**

### CODE REVIEW

**Review by dovholuknf — APPROVED** [review]

**Comment by ckdarby** [comment]
@qrkourier  & @dovholuknf nice, for the next release are the other docker containers going to be complete? Such as the controller, router and tunneler?

I'm currently playing around with building out a helm chart for this.

**Comment by dovholuknf** [comment]
@qrkourier is working through getting a helm chart in place right now. 'when' - is hard to say but we've started to put time into making it happen. another community member had commented on an issue that they had given it a shot and said they were here: https://github.com/marvkis/openziti-helm-charts/tree/controller-router-charts/

Ken's taking a look at those and trying to use them as starting point

**Comment by qrkourier** [comment]
@ckdarby Next release here will produce the official images, and meanwhile you can start playing with 

## stuff self-hosting the Ziti stack in K8s

* Images: pre-release for [cli](https://hub.docker.com/repository/docker/kbinghamnetfoundry/ziti-cli/general) (the base image), [controller](https://hub.docker.com/repository/docker/kbinghamnetfoundry/ziti-controller/general), [router](https://hub.docker.com/repository/docker/kbinghamnetfoundry/ziti-router/general)
* Helm: [my fork's branch](https://github.com/qrkourier/openziti-helm-charts/tree/controller-router-charts/) is based on [marvkis's fork's branch](https://github.com/marvkis/openziti-helm-charts/tree/controller-router-charts/) and represents my effort to integrate their contribution into [the official Helm charts repo](https://github.com/openziti/helm-charts/).

## stuff for publishing cluster workloads

* [ingress](https://docs.openziti.io/docs/reference/tunnelers/linux/container/#kubernetes-deployments-for-openzitiziti-host)
* [egress](https://docs.openziti.io/docs/reference/tunnelers/linux/container/#kubernetes-deployments-for-openzitiziti-edge-tunnel)

**Comment by qrkourier** [comment]
> @qrkourier & @dovholuknf nice, for the next release are the other docker containers going to be complete? Such as the controller, router and tunneler?

@ckdarby Additionally, for the ingress/egress use cases for Ziti please check out the image used in that linked doc: `openziti/ziti-edge-tunnel`. That's the preferred tunneler (`ziti-edge-tunnel`) running in the official tunneler image. I know it's a little surprising and confusing, but `openziti/ziti-tunnel` image is actually legacy and I've only updated it to preserve some more fringe use cases, mostly for reverse compatibility. The Helm chart for cluster ingress that's in that linked doc uses the preferred image.

**Pull request merged**
